### ISSUE TITLE
Update compodoc dependences -> deprecated warning

### ISSUE THREAD

**Issue by meriturva** [compodoc/gulp-compodoc#2]
I guess package.json has to be updated due to:

`npm WARN deprecated compodoc@0.0.41: Compodoc has moved to @compodoc/compodoc`

anyway...so thanks for your cool project!

**Comment by vogloblinsky** [comment]
Fixed in version 0.0.5

**Comment by meriturva** [comment]
i guess that you have also to change: **compodocModule = require('compodoc')**, otherwise big error here!
Please reopen issue!
So thanks.
Diego

**Comment by vogloblinsky** [comment]
Fixed in version 0.0.6
