### ISSUE TITLE
[BUG] name ignored in options

### ISSUE THREAD

**Issue by markoliverbrawn** [compodoc/gulp-compodoc#3]
Hi, 
I have the following task:
```
return gulp.src('resources/typescript/**/*.ts')
        .pipe(compodoc({
            hideGenerator: true,
            output: 'resources/typescript/documentation/generated/',
            toggleMenuItems: 'all',
            tsconfig: 'tsconfig.json',
            theme: 'readthedocs',
            name: 'My Documentation Title'
        }));

```
But "My Documentation Title" is being ignored and it's defaulting to "Application documentation". 

Any idea why?

I'm using: 

```
"@compodoc/compodoc": "^1.0.0-beta.10",
"@compodoc/gulp-compodoc": "0.0.6",
```

**Comment by vogloblinsky** [comment]
Internally compodoc use `documentationMainName` instead of `name`.
Using gulp-compodoc, we don't pass by CLI interface that makes the link.
I will fix that to expose correctly stuff for gulp-compodoc also.
For now, use `documentationMainName`, and with 1.0.0-beta.11 it will be `name`again.

**Comment by markoliverbrawn** [comment]
Cheers fella,

That sorted it. Have added both.
