### ISSUE TITLE
[BUG] Cannot pipe another tasks at end

### ISSUE THREAD

**Issue by jhuss** [compodoc/gulp-compodoc#4]
I'm trying to do:

```javascript
return gulp.src('./copy-src/**/*.ts')
    .pipe(compodoc({
        output: './docs/',
        tsconfig: './tsconfig.json',
        theme: 'readthedocs',
        serve: false
    }))
    .pipe(del('./copy-src/'));
```

or anything else pipe task after, hasn't been called

**Comment by tinesoft** [comment]
Hi @vogloblinsky ,

i'm still facing the issue with current `v0.0.7` of the plugin...
My [task](https://github.com/tinesoft/ngx-wow/blob/master/gulpfile.js#L501) is somehow similar  to the one in the above issue description: the task piped after `compodoc` is not called...

**Comment by vogloblinsky** [comment]
Hi @tinesoft 
I clone your project, install everything, launch gulp __deploy:demo__ and gulp started well __push:demo__ task. Where should it breaks ?

**Comment by tinesoft** [comment]
Hi @vogloblinsky,

Thanks for the fast answer.
Actually, with the current form of the `gulp deploy:demo` task ( launched using `runSequence`)
the task after `build:doc`seem to be started, but it never runs:
![image](https://user-images.githubusercontent.com/4053092/32035379-2948a874-ba19-11e7-8ec5-04ca353e206c.png)

when i remove `'build:doc'`, from the list, the next task is run successfuly.
![image](https://user-images.githubusercontent.com/4053092/32035580-982df8a6-ba1a-11e7-92c7-29a1a181679a.png)

**Comment by vogloblinsky** [comment]
0.0.8 fix this correctly

**Comment by tinesoft** [comment]
Hi @vogloblinsky ,

Thanks for the fix 👍 , i can confirm it is working fine now!
