### ISSUE TITLE
Event Stream Version Has Security Vulnerabilities

### ISSUE THREAD

**Issue by FarajiA** [compodoc/gulp-compodoc#8]
Hey folks, it looks like the version of Event Stream you're using as a dependency has a dependency `flatmap-stream` that is malicious. Updating Event Stream to v4  would be best. 

Thanks!

![event-streamversion](https://user-images.githubusercontent.com/5041718/49095639-86df5200-f22e-11e8-90ad-00c9eec425a9.png)

**Comment by vogloblinsky** [comment]
I will release a new version of compodoc tonight, and will update this one too.

**Comment by vogloblinsky** [comment]
fixed by https://github.com/compodoc/gulp-compodoc/commit/44e9a06597dc6890bacf1ea7eedd1e25d38c9347
